[package]
  cjc-version = "1.0.0"
  name = "aspire_identity_protocols_oidc"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}
  
[dependencies]
  aspire_identity_tokens = { path = "../aspire_identity_tokens"}
  aspire_identity_protocols = { path = "../aspire_identity_protocols"}

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX}"]

[target.x86_64-unknown-linux-gnu.bin-dependencies]    
  path-option = ["${CANGJIE_STDX}"]  
