package soulsoft_security_tokens_jwt

public class SecurityAlgorithms {
    public static let HmacSha256 = "HS256"
    public static let HmacSha384 = "HS384"
    public static let HmacSha512 = "HS512"

    public static let EcdsaSha256 = "ES256"
    public static let EcdsaSha384 = "ES384"
    public static let EcdsaSha512 = "ES512"

    public static let RsaSha256 = "RS256"
    public static let RsaSha384 = "RS384"
    public static let RsaSha512 = "RS512"
}