[package]
  cjc-version = "0.60.5"
  name = "soulsoft_extensions_logging_configuration"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  soulsoft_extensions_logging = { path = "../soulsoft_extensions_logging"}
  soulsoft_extensions_configuration = { path = "../soulsoft_extensions_configuration"}