[dependencies]
  soulsoft_asp_http = { path = "../soulsoft_asp_http"}
  soulsoft_extensions_injection = { path = "../soulsoft_extensions_injection"}
  soulsoft_extensions_healthchecks = { path = "../soulsoft_extensions_healthchecks"}
[package]
  cjc-version = "0.58.3"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "soulsoft_asp_healthchecks"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
