[dependencies]
  soulsoft_asp_http = { git = "https://gitcode.com/soulsoft/soulsoft_asp_http.git", branch = "main"}
  soulsoft_extensions_injection = { git = "https://gitcode.com/soulsoft/soulsoft_extensions_injection.git", branch = "main"}
  soulsoft_extensions_healthchecks = { git = "https://gitcode.com/soulsoft/soulsoft_extensions_healthchecks.git", branch = "main"}
[package]
  cjc-version = "0.58.3"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "soulsoft_asp_healthchecks"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
