
[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "aspire_web_hosting"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

[dependencies]
  aspire_web_http = { path = "../aspire_web_http"}
  aspire_identity_claims = { path = "../aspire_identity_claims"}
  aspire_extensions_hosting = { path = "../aspire_extensions_hosting"}
  aspire_extensions_logging = { path = "../aspire_extensions_logging"}
  aspire_extensions_options = { path = "../aspire_extensions_options"}
  aspire_extensions_injection = { path = "../aspire_extensions_injection"}
  aspire_extensions_configuration = { path = "../aspire_extensions_configuration"}
  aspire_extensions_logging_configuration = { path = "../aspire_extensions_logging_configuration"}

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["${CANGJIE_STDX}"]

[target.x86_64-unknown-linux-gnu.bin-dependencies]    
  path-option = ["${CANGJIE_STDX}"]