[package]
  cjc-version = "1.0.0"
  name = "aspire_web_authentication"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  aspire_web_http = { path = "../aspire_web_http"}
  aspire_identity_claims = { path = "../aspire_identity_claims"}
  aspire_extensions_logging = { path = "../aspire_extensions_logging"}
  aspire_extensions_options = { path = "../aspire_extensions_options"}
  aspire_extensions_injection = { path = "../aspire_extensions_injection"}